### PR TITLE
Fix/mailer links

### LINKED ISSUE #10: Link in the registration confirmation email
**Description of the bug**
When I receive the registration confirmation email, the link in the email does not redirect me to the platform as expected. Instead I have a warning the the url is no valid (http:///friendly_signup/confirmation_codes?confirmation_token=y52EEQ64-nBPfSWdw4AQ).

**To reproduce**
1. Register on the platform 
2. Receive and open the registration confirmation email
3. Click on the link in the body of the email
4. You are redirected to a warning that the url is not valid

**Screenshots** 
Link displayed in the registration confirmation email :
Capture d’écran 2022-10-05 à 15 37 57

When clicking on the link : 
Capture d’écran 2022-10-05 à 15 40 23

### PR DESCRIPTION
**Pull request by AyakorK**
Hello ! 

I'll submit to you a fix of the issue about mail's links that were sent with the confirmation code. 
Actual issue was that the link that we showed was a link that worked only on local because we matched it with the actual route (localhost:3000/friendly_signup/...), but in the case where we opened it in an other mail manager than /letter_opener, we saw that it redirected to https://friendly_signup/... because we actually never specified the root. 

If there are some changes that you want me to do feel free to tell me about it !

### CODE REVIEW

**Review by paulinebessoles — APPROVED** [review]

File: app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb [hunk 1]
```diff
@@ -17,6 +18,16 @@ def confirmation_instructions(user, opts)
...
       end
+
+      private
+
+      def confirm_path_url
+        "#{root_url}#{decidim_friendly_signup.confirmation_codes_path(confirmation_token: @token)}"
+      end
+
+      def root_url
+        @root_url ||= decidim.root_url(host: @user.organization.host)[0..-2]
```
Comment (Quentinchampenois) [inline app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Hello, I am not sure to understand why we should remove last chars ?

Comment (Quentinchampenois) [reply app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Is it to remove the last `/` of the `decidim.root_url` ?

Comment (AyakorK) [reply app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Actually if we only print this part of the code
```decidim.root_url(host: @user.organization.host)``` we will have at the end a ```/```and a space after it.
To take rid of that, we suppress the two last chars of the url which could have destroy the url if we had put a route after it (the route of friendly_signup confirm)

Comment (AyakorK) [reply app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Capture d’écran 2022-11-08 à 10 07 32

Here is the preview of what it looked like if we didn't get rid of the last chars

Comment (Quentinchampenois) [reply app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Alright, I am just surprised to see a trailing whitespace returned by `decidim.root_url`, I think it is more safe to strip the trailing whitespaces rather than arbitrary remove 2 chars 

```suggestion
        @root_url ||= decidim.root_url(host: @user.organization.host).strip[0..-1]
       
```

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]

File: app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb (hunk 1 above)
Comment (Quentinchampenois) [reply app/mailers/decidim/friendly_signup/confirmation_codes_mailer.rb:29]: Because it ends with '&nbsp' char we can't use `strip`

**Review by Quentinchampenois — APPROVED** [review]
